services:
  - type: web
    name: chatbot-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://chat-bot-cbwi.onrender.com/api
